# Notebook Jupyter cu integrare MLflow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-test-workspace
  namespace: user-example-com
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: mlflow-test-notebook
  namespace: user-example-com
  labels:
    mlflow: "enabled"
spec:
  template:
    spec:
      serviceAccountName: default-editor
      containers:
      - name: mlflow-test-notebook
        image: jupyter/scipy-notebook:latest
        command: ["start-notebook.sh"]
        args:
          - "--NotebookApp.base_url=/notebook/user-example-com/mlflow-test-notebook"
          - "--NotebookApp.allow_origin='*'"
          - "--NotebookApp.disable_check_xsrf=True"
          - "--NotebookApp.token=''"
          - "--NotebookApp.password=''"
        env:
        # Variabile MLflow injectate automat
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service.mlflow.svc.cluster.local:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio.mlflow.svc.cluster.local:9000"
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin123"
        - name: MLFLOW_EXPERIMENT_NAME
          value: "kubeflow-experiments"
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        volumeMounts:
        - name: workspace
          mountPath: /home/jovyan
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: mlflow-test-workspace
      - name: shm
        emptyDir:
          medium: Memory
