# PodDefault - injectează automat variabilele MLflow în Notebook-uri
# Când creezi un Notebook, vei putea selecta "MLflow Integration"
---
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: mlflow-integration
  namespace: user-example-com  
spec:
  desc: "MLflow tracking integration - Auto-configure MLflow environment variables"
  selector:
    matchLabels:
      mlflow: "true"
  env:
  - name: MLFLOW_TRACKING_URI
    value: "http://mlflow-service.mlflow.svc.cluster.local:5000"
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://minio.mlflow.svc.cluster.local:9000"
  - name: AWS_ACCESS_KEY_ID
    value: "minioadmin"
  - name: AWS_SECRET_ACCESS_KEY
    value: "minioadmin123"
  - name: MLFLOW_EXPERIMENT_NAME
    value: "kubeflow-experiments"
